### ISSUE TITLE
CSV

### ISSUE THREAD

**Issue by adamcoder2** [Afonsocraposo/ppg#4]
I'm working in a fully integrated medical diagnosing project which makes me focus on collecting PPG data through fingertip in-camera, So I wonder if you can guide me how to collect ppg data collected using this code in CSV File so I can process this data in python code :)

**Comment by afonsocraposo** [comment]
You have to store the values in an array and then save them into a csv file using the package:
https://pub.dev/packages/csv
You then can use the package:
https://pub.dev/packages/path_provider
To write your file to an accessible folder so you can retrieve it and process the data in python code
