### ISSUE TITLE
github.com/Renesanse/plugins.git not found

### ISSUE THREAD

**Issue by bbrattoli** [Afonsocraposo/ppg#6]
Thank you for sharing your project! It was suggested to me by Medium. However, I cannot run it because the flash_light plugin is missing. Could you help me with this issue? Here is the log of the error:
```

/usr/local/flutter/bin/flutter --no-color packages get
Running "flutter pub get" in PPG...                             
Git error. Command: git clone --mirror https://github.com/Renesanse/plugins.git /usr/local/flutter/.pub-cache/git/cache/plugins-9c3ccebc0078f4dca69fbb5d5724e2834a7436ef

Cloning into bare repository '/usr/local/flutter/.pub-cache/git/cache/plugins-9c3ccebc0078f4dca69fbb5d5724e2834a7436ef'...

remote: Repository not found.

fatal: repository 'https://github.com/Renesanse/plugins.git/' not found
```

**Comment by afonsocraposo** [comment]
Hi!
It seems like Renesanse deleted his fork.
Try using this package instead, since it allows for flash control during ImageStream:
https://pub.dev/packages/flutter_better_camera
