### ISSUE TITLE
Role of the "alpha" variable

### ISSUE THREAD

**Issue by nbalex04** [Afonsocraposo/ppg#7]
What is the goal in doing this ?
```dart
this._bpm = ((1 - _alpha) * _bpm + _alpha * _bpm).toInt();
```
Thanks for the repo by the way !

**Comment by afonsocraposo** [comment]
It should be:
this._bpm = ((1 - _alpha) * this._bpm + _alpha * _bpm).toInt();

The alpha works as a lowpass filter and attenuates rapid variations of the signal.

If alpha is 1:
this._bpm = ((1 - 1) * this._bpm + 1 * _bpm).toInt()
or
this._bpm = (this._bpm).toInt()
Which means that the _bpm hold the last calculated value.

If alpha is 0.1:
this._bpm = ((1 - 0.1) * this._bpm + 0.1 * _bpm).toInt()
or
this._bpm = ((0.9) * this._bpm + 0.1 * _bpm).toInt()
Which means that last calculated _bpm value will affect the overall _bpm value, but only a little.
