### ISSUE TITLE
How to Check Oxygen Saturation

### ISSUE THREAD

**Issue by yusriltakeuchi** [Afonsocraposo/ppg#9]
Can we check Blood oxygen saturation measured by pulse oximetry with this code?
In this source code just showing how to get BPM, but how if we want to get the oxygen saturation?

**Comment by afonsocraposo** [comment]
Hi, it's not possible to check the blood oxygen saturation with the code as it is.
You can check [this article](https://www.christianholz.net/2018-embc18-holz_ofek-Doubling_the_Signal_Quality_of_Smartphone_Camera_Pulse_Oximetry_Using_the_Display_Screen_as_a_Controllable_Selective_Light_Source.pdf) for more details.
